[workspace]
members = [
	"core",
	"integration_tests",
	"program",
]

resolver = "2"

[workspace.dependencies]
solana-program = "~2.1"
solana-program-test = "~2.1"
solana-sdk = "~2.1"
solana-rpc-client = "~2.1"
solana-rpc-client-api = "~2.1"
