[env]
HELLO_WORLD_NCN_PROGRAM_ID = "DXWJEC5JBUeNurpo7wPDUHGhDWnjkTzUiV3gp2D9y8zr"
RESTAKING_PROGRAM_ID = "RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"
VAULT_PROGRAM_ID = "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
