[package]
name = "hello-world-ncn-program"
description = "Hello World NCN Program"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
name = "hello_world_ncn_program"

[features]
no-entrypoint = []

[dependencies]
borsh = { workspace = true }
hello-world-ncn-sdk = { workspace = true }
jito-jsm-core = { workspace = true }
solana-program = { workspace = true }
solana-sdk = { workspace = true }
